combustion-inc/combustion-android-ble

- build.gradle
- combustion-android-ble/build.gradle
- Setup publishing in build script.
- Set initial version number.
> Setup Package Publishing

- build.gradle
- combustion-android-ble/build.gradle
- Feature complete and documented.
- First public build of framework for integration and testing with other components.
> Alpha Release of Android Framework

- README.md
- Integration JitPack hosting of library against Example and Diagnostic apps.
- Documentation updates for JitPack integration.
> Alpha Build Integration Testing

- README.md
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/LogManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/ProbeTemperatureLog.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/Session.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/DebugSettings.kt
- Integration testing in preparation for the v0.0.2 build.
- Resolve issue when resuming upload after a disconnection (CMB-APPS-52)
- Documentation updates.
> v0.0.2 Integration Testing

- combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbeScanner.kt
- Making suspending portion of scanning public in ProbeScanner.
- Users of the API are required to manage the coroutine scope for the suspend call.
> Suspend Version of ProbeScanner

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/LogManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/ProbeTemperatureLog.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/Session.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionService.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/LoggedProbeDataPoint.kt
- Add wall clock timestamps values to logged data points.
- Fix typo in method name.
Please test using this branch:
https://github.com/combustion-inc/combustion-android-example/pull/12
> Add Timestamps to Logged Data Points

- combustion-android-ble/build.gradle
- combustion-android-ble/src/main/java/inc/combustion/framework/Combustion.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/Device.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/Extensions.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/DataClasses.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/LogManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/ProbeTemperatureLog.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/Session.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionService.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt
- Ability to export data as CSV.
- Add in desugar library for newer DateTime calls.
- Fix issue with flow replay buffer.
- Setup versioning based on git describe.
Please test against this branch of the open source app:
https://github.com/combustion-inc/combustion-android-example/pull/13
> Export Data as CSV

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/DeviceStatus.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeAdvertisingData.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeStatus.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/SimulatedProbeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/LogResponse.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/Response.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/SessionInfoResponse.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/SetColorResponse.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/SetIDResponse.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/SetPredictionRequest.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/SetPredictionResponse.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/LogManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/ProbeTemperatureLog.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/Session.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/LoggedProbeDataPoint.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/PredictionStatus.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/Probe.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbeHopCount.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbePredictionMode.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbePredictionState.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbePredictionType.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbeVirtualSensors.kt
- Support deserializing message updates for prediction.
- Updates to `Probe` data class and additional enums in public packages.
> Preliminary Prediction Support

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/LogResponse.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/Response.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/SessionInfoResponse.kt
- Cherry-pick code from develop to use the packet length in the response when processing UART response messages.
Tested with probe firmware `v0.8.2` and `v0.9.0`
> Prediction Message Forwards Compatibility

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/Device.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/LogManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/Probe.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbeVirtualSensors.kt
- Have probe data class behave more like iOS
> DROID-62: Improve Probe Data Class

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/DataLinkArbitrator.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/BleDevice.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/ProbeBleDevice.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/ProbeBleDeviceBase.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/RepeatedProbeBleDevice.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/UartBleDevice.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeProbeStatusRequest.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeRequest.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeResponse.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/LogManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/Session.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionService.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/Probe.kt
> DROID-98: meatnet probe support, DROID-85: timeouts

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeStatus.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/LogResponse.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/LoggedProbeDataPoint.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/PredictionLog.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/PredictionStatus.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbePredictionMode.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbePredictionState.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbePredictionType.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbeVirtualSensors.kt
- Processes Prediction Log structures and add them to the temperature log.
- Update CVS to Version 4 
- Stop supporting pre-production protocol versions.
> DROID-4: CSV v4 Support

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
- Fix device scanning when not using MeatNet.
Test Cases:
- First time launch (e.g. permissions prompt), Bluetooth enabled.
- First time launch (e.g. permissions prompt), Bluetooth disabled.
- Subsequent launch (e.g. permissions already accepted), Bluetooth enabled, and Bluetooth disabled.
See related PR in combustion-android-example.
> DROID-139: Scan Management when MeatNet is Not Enabled

- combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionService.kt
- Resolve crashlytics crash from Play Store automated tests.
Testing Notes:
- The issue can be reproduced on older emulators; e.g. Pixel 4 API 29.
- Newer emulators, e.g. Pixel XL API 33, don't cause the issue because they emulate Bluetooth.
> DROID-125: Support Emulators w/o Bluetooth

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
- Not refreshing session information.
> DROID-158 Bug Fix

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/RepeatedProbeBleDevice.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadFirmwareRevisionRequest.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadFirmwareRevisionResponse.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadHardwareRevisionRequest.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadHardwareRevisionResponse.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadLogsRequest.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadLogsResponse.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadModelInfoRequest.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadModelInfoResponse.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadSessionInfoRequest.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadSessionInfoResponse.kt
- Added Read Firmware Rev, Hardware Rev, and Session Info Message req/resp
- Added MeatNet Model Info req/resp definitions; formatting changes
- Added MeatNet Log req/resp; added trim to Hardware Revision string
> DROID-167: MeatNet add new node specific messages

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/LogManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/Probe.kt
Adding hopCount and recordsDownloaded to published probe class
> DROID-187: Engineering details screen updates

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/scanning/DeviceScanner.kt
- Buffer and change overflow policy for advertisements.
> DROID-154: Address Crashlytics ANR

- combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionService.kt
- In some cases onDestroy of service is called before NetworkManager is initialized.
- Handle that exception when cleaning up NetworkManager in onDestroy.
> DROID-200: Address Crashlytics

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/SimulatedProbeBleDevice.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionService.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/PredictionStatus.kt
- Please test with this draft PR for the Example App: https://github.com/combustion-inc/combustion-android-example/pull/33
- That PR uses the simulated probe API.
> DROID-135: Simulated Probe Support

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/Probe.kt
- Add isPredicting field.
- Add predictionStale field.
> DROID-193: Add fields to Probe data class

- combustion-android-ble/build.gradle
- settings.gradle
- See related PR in example app.  https://github.com/combustion-inc/combustion-android-example/pull/34
> DROID-215: Use snapshot kable build

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/RepeatedProbeBleDevice.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeUARTMessage.kt
- Require multiple ping failures.
- Quite node warning message.
> DROID-227: MultiNode Integration Testing

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/UartBleDevice.kt
- Cancel message completion timeout whenever we start a request with a new MeatNet request ID.
> DROID-253: Resolve Bug

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
- Publish current connection state on each status notification so it doesn't go stale.
- Don't publish NO_ROUTE connection state during log upload, since we expect session info responses to get dropped when there is lots of traffic over MeatNet.
> DROID-320: Resolve Issues with Incorrect Connection State

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/BleDevice.kt
Tested with multiple devices, confirmed through debug view that RSSI is being updated.
> DROID-319: Use advertising data as source of RSSI instead of direct read

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/DataLinkArbitrator.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/JobManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/BleDevice.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/DfuBleDevice.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/ProbeBleDevice.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/RepeatedProbeBleDevice.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/scanning/DeviceScanner.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/LogManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionService.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbeDiscoveredEvent.kt
@angrygorilla please take a look at this as well.
> DROID-282: Implement association/linking

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/Probe.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbeTemperatures.kt
- Change scoping of some utility functions so they are available to applications.
> DROID-352: Framework Scoping

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/Extensions.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/PredictionManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/ProbeBleDevice.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/ProbeBleDeviceBase.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/RepeatedProbeBleDevice.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/scanning/BaseAdvertisingData.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/scanning/CombustionAdvertisingData.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/utils/DefaultLinearizationTimerImpl.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/utils/PredictionManager.kt
- combustion-android-ble/src/test/java/inc/combustion/framework/service/utils/PredictionManagerTest.kt
Note that this is built on DROID-401.
> DROID-412: Add linearization processing to cloud data

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
- There is a requirement to display a new message when node update is critical but app's device list screen was not observing any node firmware states
- Add missing/removed publishing of node's firmware state
**Note, required for app PR https://github.com/combustion-inc/combustion-android-prod/pull/292**
Critical update message is displayed and wifi device is still detected
https://github.com/user-attachments/assets/fda6aae8-ce6a-405c-bbe8-ae49108e44a2
> DROID-562 : Fix node firmware state not being observed

- combustion-android-ble/src/main/java/inc/combustion/framework/Extensions.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/GaugeTemperatureLog.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/ProbeTemperatureLog.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/LoggedDataPoint.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/LoggedGaugeDataPoint.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/LoggedProbeDataPoint.kt
- merge to feature branch
- matching app PR: https://github.com/combustion-inc/combustion-android-prod/pull/321
- support gauge rest calls to cloud
- support parsing gauge data from firebase
> DROID-583: add cloud sync support for gauge data

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/BleManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/GaugeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/BleDevice.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadGaugeLogsResponse.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/LogManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/log/Session.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/LoggedGaugeDataPoint.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/LoggedProbeDataPoint.kt
- tweak downloading of ble logs from gauge
- fix providing gauge logs
- fix gauge disappearing when: launch app from android studio -> press/gesture back -> releunch app from phone.
https://github.com/user-attachments/assets/67c662c1-e81d-421a-87f9-ddd71b9325e2
> Fix gauge related non-UI bugs

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/GaugeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeHeartbeatRequest.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt
Resolve remaining gauge TODOs to prepare feature branch for merging into develop
> DROID-631 : resolve remaining gauge todos.

- combustion-android-ble/src/main/java/inc/combustion/framework/ble/GaugeManager.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/GaugeStatus.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/SimulatedGaugeBleDevice.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/ble/scanning/GaugeAdvertisingData.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/Gauge.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/Probe.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbeBatteryStatus.kt
- combustion-android-ble/src/main/java/inc/combustion/framework/service/SpecializedDevice.kt
Remove Gauge battery percentage
Simplify detecting low battery for device
> DROID-688: Remove Gauge battery percentage
