combustion-android-ble/build.gradle
combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeAdvertisingData.kt
combustion-android-ble/src/main/java/inc/combustion/framework/log/DataClasses.kt

updated minSdk to 24 which uncovered a couple API incompatibilities. 
- There was a bluetooth isScannable method that was introduced in API 26, to handle this we just return true for API versions less than 26
- There are several time/date/formatting methods that were added in Java 8 that we were using. To work around that I am using some older java.util and java.text modules to create some timestamps for session id creation.  
There are some issues testing this min version with our app in a emulator currently.

Update minSdk to 24

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/BitFunctions.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/Device.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/DeviceStatus.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeAdvertisingData.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/SimulatedProbeManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/log/LogManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/log/ProbeTemperatureLog.kt
combustion-android-ble/src/main/java/inc/combustion/framework/log/Session.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionService.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/Probe.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbeColor.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbeID.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbeMode.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbeTemperatures.kt

- Support Instant Read Mode Device Status and Advertising Packets.
- Read Probe ID and Probe Color.  UART commands to set ID and color are pending.
- Filter out timers when publishing Combustion Devices to the Discovered Probes Flow.
- Fixes for CMB-APPS-60 and CMB-APPS-58.
Please use `feature/instant_read_modecolor_timer` branch in `combustion-android` when testing.

Instant Read, Probe ID, Probe Color, Timer Support

---

.idea/gradle.xml
README.md
combustion-android-ble/build.gradle
combustion-android-ble/src/main/AndroidManifest.xml
combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeAdvertisingData.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionService.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbeScanResult.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbeScanner.kt

- Ability to optionally launch and run the Combustion Service as a foreground service.
- Calling app is responsible for creating the `Notification` and passing that into the service on start.
- Passing in null for the `Notification` results in the service being run in the background.
- Add `ProbeScanner` and `ProbeScanResult` to the public framework API to allow calling apps to scan for and identify Combustion probes independent of the Combustion Service.
Please test with `feature/foreground-service_and_scanning` in `combustion-android` repo.  Related PR is [here](https://github.com/combustion-inc/combustion-android/pull/26)  Example app updates are pending.

Foreground Service & ProbeScanner

---

combustion-android-ble/src/main/java/inc/combustion/framework/log/LogManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionService.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/DebugSettings.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt

- Incorporate reference counting in the DeviceManager to better handle the lifecycle management APIs across multiple activities.
- README.md in the example project explains the lifecycle management guidelines.
Please test with `combustion-android-ble` branch `feature/service_lifecycle`

Service Lifecycle

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/Extensions.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/LogRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/Request.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/Response.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/SessionInfoRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/SetColorRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/SetIDRequest.kt

- Check CRC on response messages.
- Calculate and send CRC on request messages.
- Firmware greater than v0.8.2 requires this feature.
Tested data transfer, set probe id, and probe color.

Add CRC Calculation and Checking to UART Messages

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionService.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbePredictionState.kt

- API for setting and canceling a prediction.
- Change Warming State to Cooking State.
Requires this Probe FW
https://github.com/combustion-inc/meat-dagger-firmware/pull/128
Requires this Android Example App
https://github.com/combustion-inc/combustion-android-example/pull/20

Set Prediction

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/DataLinkArbitrator.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/BleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/DeviceInformationBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/ProbeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/ProbeBleDeviceBase.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/RepeatedProbeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/UartBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/NodeFirmwareState.kt

- Create DataLinkArbitrator
- Heuristics to determine if a device should be connected to or disconnected from.
- Connection and Disconnection
- Read Device Information on Connection and publish.
- Flow for publishing node firmware details upon connection.
- MeatNet: automatic connection and reconnection to timers.
- Auto-Reconnect: !MeatNet with autoReconnect = true, automatic reconnect after framework call to connect.  Continue to reconnect until framework call disconnect.

DROID-91: MeatNet connection management

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionService.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt

- Make NetworkManager a singleton that is initialized when the service is started.
- Correctly clear shared flow when devices are cleared.

DROID-33: Improvements to Service Lifecycle Management

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/DataLinkArbitrator.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/BleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/DfuBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/RepeatedProbeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/LogResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeProbeStatusRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadLogsRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadLogsResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadSessionInfoResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeSetPredictionResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeUARTMessage.kt
combustion-android-ble/src/main/java/inc/combustion/framework/log/DataClasses.kt
combustion-android-ble/src/main/java/inc/combustion/framework/log/LogManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/log/ProbeTemperatureLog.kt
combustion-android-ble/src/main/java/inc/combustion/framework/log/Session.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/DebugSettings.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceConnectionState.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/Probe.kt

- MeatNet log transfer messages.
- Add in No Route connection state.
- Add in ping for checking when there isn't a route through the network.
- Arbitrate connection state, fw ver, hw ver, sku/lot.
- Fix issues when reading fw ver, hw rev, sku/lot from repeaters.
Not required, but should probably use the corresponding prod app branch.

DROID-179: MeatNet Log Transfer

---

combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt

- Handle situations where the service isn't fully started when making a call to stop the service since start API is asynchronous.

DROID-201: Address Crashlytics

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionService.kt

- Use proper API to start service when app is in the background on newer versions of Android.

DROID-205: Address Crashlytics

---

combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionService.kt

- Bug generated an ANR -- since null is passed in for the notification, we can't start the service as foreground.
Can test using the example app and using the boolean flag in `MainActivity.kt` that disables foreground service.

DROID-222: Handle Null Service Notification

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/DataLinkArbitrator.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt

- Fix issue with arbitrated connection state.  
- directLink only returns a reference when connected, we need to use probeBleDevice instead to arbitrate.

DROID-224: Display Advertised Temperatures

---

.idea/kotlinc.xml
combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/log/ProbeTemperatureLog.kt

- added new check of connectionState in handleConenctionState to reset sessionInfo when not DeviceConnectionState.CONNECTED
Issue was more prevalent if you initially take a probe from a booster, allow it connect and become repeated through the booster, place the probe back in the booster, allow disconnect of booster to complete, then finally remove the probe from the booster and allow it become repeated through the booster again. The new session information would not get updated for that probe so it would use the older sequence min/max and also session id value.

DROID-235: New Sessions are not being added on probe reconnection through a Node/Repeater

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/DfuBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/dfu/DfuManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/dfu/DfuState.kt

- updated DfuBleDevice to have a enabled/disabled state which is reflected via DfuState
- update DfuManager to have a attribute that reflects if a DFU has been started
- added completion callback that is called when a DFU ends with Success, Error, or Aborted; All other devices get re-enabled

DROID-117: Add ability to only have one DFU running at a time

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/DataLinkArbitrator.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/ProbeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/ProbeBleDeviceBase.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/RepeatedProbeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/SimulatedProbeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/UartBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeHeartbeatRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeProbeStatusRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadFirmwareRevisionRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadFirmwareRevisionResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadHardwareRevisionRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadHardwareRevisionResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadLogsRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadLogsResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadModelInfoRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadModelInfoResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadSessionInfoRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadSessionInfoResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeSetPredictionRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeSetPredictionResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeUARTMessage.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/DebugSettings.kt

- Use worse-case 30s message timeout for MeatNet messages.
- Send Set Prediction Request to all nodes and handle the first response.
- Add message trace filter
- Add optional request id to message handler class.
- Add Node UART message tracing.
- Fix SetPredictionResponse handling.

DROID-234, DROID-192 

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/DataLinkArbitrator.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/DeviceInformationBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/ProbeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/ProbeBleDeviceBase.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/RepeatedProbeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/SimulatedProbeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/UartBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadLogsResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadSessionInfoResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/log/DataClasses.kt
combustion-android-ble/src/main/java/inc/combustion/framework/log/LogManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/log/ProbeTemperatureLog.kt
combustion-android-ble/src/main/java/inc/combustion/framework/log/Session.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/Probe.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/ProbeUploadState.kt

- DROID-241, DROID-243: Refactor how missing records are determined.
- DROID-241, DROID-243: Transition to upload complete when 2 device status messages have been received w/o a log response. 
- DROID-238: Setup node message completion handling based on request id.
- DROID-238: 30 second session info response indicates no route.
- DROID-238: Send Requests to all nodes and handle first response (excluding log requests)
- DROID-238: Remove Monitor MeatNet coroutine (i.e. SessionInfo ping).
- DROID-238: Accept ProbeStatus messages over any MeatNet node and update arbitration logic.
- DROID-238, DROID-242: Remove message handling based on serial number.
- DROID-238, DROID-242: Request all device information (until response is received) and session info on every probe status message.
- …

DROID-238, DROID-241, DROID-242, DROID-243, DROID-236

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/BleDevice.kt

- Re-enable code to poll on RSSI while connected.
- Change poll rate from 2s to 0.5s.
Tested by observing RSSI while connected using the debug mode in the prod app.  I tried repeatedly setting predictions while downloading logs, which is the original cause of the issue. I believe that recently updating the Kable dependency to the latest release resolved this issue for us.

DROID-106: Read RSSI while connected

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/log/LogManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/Probe.kt

- Make min/max sequence number optional to be consistent with iOS.
- Add a deprecation warning to the existing fields.
https://github.com/combustion-inc/combustion-android-prod/pull/109

DROID-278: PoC Producing/Consuming Probe Status

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt

* Fix a problem where new functionality isn't available because the app thinks it's old firmware.
* Fix issue where probe product type wasn't set

DROID-296: Invalidate probe FW version on return from DFU

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/BleDevice.kt

UART writes would deadlock, and no commands would make it over the network.  This works around that issue and avoids the deadlock.
- Tested 2 direct connected probes.
- Tested with 3 probes and two nodes.  I do see occasional drops on the response over MeatNet, but the value made it to the probe as observed by the setting on the app/timer; so confident that the write made it to MeatNet.

Disable Read RSSI while Connected

---

combustion-android-ble/build.gradle.kts

Fixes an issue with the wrong library configuration(s) being published to jitpack. See [this slack thread](https://sasquatch-collective.slack.com/archives/C031NP7Q0ER/p1704913666052869) for more information.
Tested by setting:
```
combustionAndroidBleDevelopSnapshot = "bugfix~fix_publishing_issues-SNAPSHOT"
```
In the prod app's `libs.versions.toml` and removing `combustion.properties` in the app build to emulate the jitpack environment.

Remove publishing block from gradle build.

---

combustion-android-ble/build.gradle.kts
combustion-android-ble/src/main/java/inc/combustion/framework/service/FoodSafeData.kt
combustion-android-ble/src/test/java/inc/combustion/framework/service/FoodSafeDataTest.kt
gradle/libs.versions.toml

https://linear.app/combustion/issue/DROID-418/update-foods-integrated-mode-parameters-in-ble-framework
Update FoodSafe Integrated products to latest requirements in spreadsheet https://docs.google.com/spreadsheets/d/1oDlP5sua6cjwPci3izsTixdTFH7BUwA1mXkIBCCoqUk/edit#gid=1179861674
- Rename existing products to the new products where it makes sense
- Need to keep all deprecated products and their order, but rename them with prefix "Deprecated"
- Add the new products that did not match existing
**Does my renaming need to be more aggressive?**

DROID-418: Update FoodSafe integrated products to latest requirements

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/DataLinkArbitrator.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/RepeatedProbeBleDevice.kt

Also fix an issue with multiple MeatNet nodes.
No public API changes.

DROID-417: MeatNet node scanning timeouts

---

combustion-android-ble/src/main/java/inc/combustion/framework/service/FoodSafeData.kt

This removes deprecated integrated food types and renames the integrated food type `.Default` to `.Poultry`. There's a corresponding cloud PR [here](https://github.com/combustion-inc/combustion-cloud/pull/102).
cc @jmaha

DROID-439: Remove deprecated integrated food types.

---

combustion-android-ble/src/main/java/inc/combustion/framework/service/utils/PredictionManager.kt

See title. This bug was reported by several customers on Reddit.

Removed cap on prediction time to support low-and-slow.

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/NodeBleDevice.kt

The genericRequestHander wasn't tracking the requestId. This caused it to return responses for incorrect messages if other responses were interleaved. Passing the requestId to the wait and handle methods fixes this issue.

Fix bug with request handling

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeResponse.kt

If a response message fails the CRC check for some reason it will attempt to be parsed as a request message. This should also fail the CRC check though it is possible for the length to be incorrect since the payloadLength is stored in different locations. If this value becomes negative an exception will be thrown because its in invalid index. To prevent this from happening the framework now checks to ensure the crcData size is greater than or equal to the expected length.
This pull request includes changes to improve error handling and prevent index out of bounds errors in the `NodeRequest` and `NodeResponse` classes. Additionally, it includes necessary imports for logging.
Improvements to error handling:
* [`combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/No …

DROID-516 - Prevent exception when CRC length isn't correct

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/NodeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/GenericNodeRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt

Add support for sending generic requests to the user of the framework if they want to handle them.
This pull request introduces several changes to the `combustion-android-ble` project, mainly focusing on the handling of UART messages and the integration of `GenericNodeRequest` flows. The changes include updates to the `NetworkManager`, `NodeBleDevice`, and related classes to support the new flow and improve message handling.
* Added `mutableGenericNodeRequestFlow` to `NetworkManager` to handle generic node requests. [[1]](diffhunk://#diff-6a03f0af2d3f3d2b783cd0040dad7026ecab95b2f14fe975fc856ed7f58021efR74) [[2]](diffhunk://#diff-6a03f0af2d3f3d2b783cd0040dad7026ecab95b2f14fe975fc856ed7f58021efR167-R169)
* Exposed `genericNodeRequestFlow` as a `SharedFlow` in `NetworkManager`.
* Renamed …

Support request forwarding

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/GenericNodeRequest.kt

The GenericRequest wasn't removing the request header from the payload data and passing that along. That resulted in the size of the payload being incorrect potentially causing an out of bounds exception.

Remove request header from payload data

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/NodeBleDevice.kt

https://linear.app/combustion/issue/DROID-530/wifi-connect-times-out
https://linear.app/combustion/issue/DROID-531/synchronize-wifi-calls-to-ble-device
- Wifi related calls are timing out
- `NodeBleDevice..sendNodeRequest()` calls are not threadsafe - observed calls getting stuck callback never happening
**Note, first commit is easier to read since does not contain autoformatting**
- increase timeout to 30000millis (30s) since WIFI_CONNECT call still timeouts at 15s and fast calls will finish fast anyway
- `Semaphore`s used in `NetworkManager` to ensure a single node request at a time per node.

Increase wifi timeouts and make sendNodeRequest call threadsafe

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/NodeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/UartBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt

* Updated NodeBLeDevice to pass async GenericNodeResponse messages to the NetworkManager. 
* Updated some methods and type names to be more generic since both requests and response are now being handled.
* [`combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt`](diffhunk://#diff-6a03f0af2d3f3d2b783cd0040dad7026ecab95b2f14fe975fc856ed7f58021efL74-R74): Renamed `mutableGenericNodeRequestFlow` to `mutableGenericNodeMessageFlow` and updated its type from `GenericNodeRequest` to `NodeUARTMessage`. This change was applied to both the variable declaration and initialization. [[1]](diffhunk://#diff-6a03f0af2d3f3d2b783cd0040dad7026ecab95b2f14fe975fc856ed7f58021efL74-R74) [[2]](diffhunk://#diff-6a03f0af2d3f3d2b783cd0040dad7026ecab95b2f14fe975fc856ed7f58021efL164-R164) …

DROID-520: Added handling of async NodeResponse messages

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/NodeBleDevice.kt

it was requested to increase the timeout since the firmware has a timeout of 90s and are thinking of increasing it to 120s

DROID-538 : increase bt response timeout for wifi comms to 120s

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/BleDevice.kt

https://linear.app/combustion/issue/DROID-541/app-crashes-when-there-are-many-probes-running
Prevent `ConcurrentModificationException` when iterate over `rssiCallbacks` in `BleDevice`
- do `rssiCallbacks.toList()`to  create an immutable copy for safe iteration.

DROID-541: prevent ConcurrentModificationException when iterate over rssiCallbacks in BleDevice

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/NodeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/utils/StateFlowMutableMap.kt

https://linear.app/combustion/issue/DROID-540/wifi-devices-screen-becomes-stale
provide stateflow of connected wifi devices for app to observe for reasons:
- can remove device-polling from app
- faster app representation of framework-observed wifi device
- can remove state devices from app if no longer in stateflow
**Note, view only the second commit to not ignore the auto-format changes.**
- add `StateFlowMutableMap` to provide StateFlow with minimal changes to `NetworkManager`
- add callback for when wifi-device disconnected with `NodeBleDevice.observeDisconnected()`

Provide stateFlow of connected wifi devices

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeStatus.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeProbeStatusRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/OverheatingSensors.kt

Update to correctly handle the location of the overheating flags when the probe status is forwarded by the node. They are actually past the `hopCount` so the range used for those flags needs to be updated.
Related iOS PRs - [PR-114](https://github.com/combustion-inc/combustion-ios-ble/pull/114) and [PR-115](https://github.com/combustion-inc/combustion-ios-ble/pull/115)

DROID-560 - Fix overheating sensor flags forwareded from a node

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt

Show WiFi devices even when not linked to a probe
Solution is pretty basic and creates a dummy `ProbeManager` that manages all devices not connected to a probe.
in `NetworkManager`:
- instead of ignoring advertisements for devices with no probe (`serialNumber == REPEATER_NO_PROBES_SERIAL_NUMBER`), now add method `manageMeatNetDeviceWithProbe()` to support it
- renamed previous method to `manageMeatNetDeviceWithProbe()`
https://github.com/user-attachments/assets/078dbb8c-10da-4c07-bd5b-a6587a8dde41

DROID-552 : WiFi devices appear even if not linked to a probe

---

combustion-android-ble/src/main/java/inc/combustion/framework/service/utils/StateFlowMutableMap.kt

https://linear.app/combustion/issue/DROID-590/graph-rarely-appearing-on-samsung-phones
**Note, required for PR https://github.com/combustion-inc/combustion-android-prod/pull/305**
- add functionality to `StateFlowMutableMap` that is used in app to fix one of the samsung issues

DROID-590 : logic used in app's samsung fix

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeStatus.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/SimulatedProbeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/Probe.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/ThermometerPreferences.kt

https://linear.app/combustion/issue/DROID-595/write-power-mode-value-to-v1probe-status-and-read-from-firestore
**Note, required by PR https://github.com/combustion-inc/combustion-android-prod/pull/304**
Rename power mode related classes to match cloud requirements

DROID-595 : rename power mode related classes to match cloud requirements

---

combustion-android-ble/src/main/java/inc/combustion/framework/analytics/AnalyticsTracker.kt
combustion-android-ble/src/main/java/inc/combustion/framework/analytics/ExceptionEvent.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/dfu/DfuManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/dfu/DfuService.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt

https://linear.app/combustion/issue/DROID-613/kotlinuninitializedpropertyaccessexception-lateinit-property
**Note, companion app PR is https://github.com/combustion-inc/combustion-android-prod/pull/313**
- Fix uninitialized property exception when auto-retry stuck dfu
- Track nonFatal exceptions
- move `DfuService.notifyActivity = notificationTarget` to `DfuManager.start()` for property `notifyActivity` to be set before auto-retry stuck DFU fires.

DROID-613 : Fix uninitialized property exception when auto-retry stuck dfu

---

combustion-android-ble/src/main/java/inc/combustion/framework/analytics/AnalyticsTracker.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/BootLoaderDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/DeviceInformationBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/SimulatedProbeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/dfu/DfuManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/dfu/PerformDfuDelegate.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/scanning/BaseAdvertisingData.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/scanning/CombustionAdvertisingData.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeHeartbeatRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionService.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/Device.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/ModelInformation.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/NodeFirmwareState.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/dfu/DfuProductType.kt
combustion-android-ble/src/test/java/inc/combustion/framework/service/ModelInformationTest.kt

Note:
- related to https://linear.app/combustion/issue/DROID-579/add-ble-interface-updates-for-gauge
- merge to feature branch
- GAUGE is now known but not yet handled -- detecting one may crash app because of `TODO()`
- app changes referencing these changes in PR https://github.com/combustion-inc/combustion-android-prod/pull/317
Since parsing GAUGE requirements contradicts current parsing implementation of `CombustionProductType`:
- rename `CombustionProductType.DISPLAY` to `CombustionProductType.NODE` since covers both display and booster
- replace `CombustionProductType.CHARGER` at `0x03u` with `CombustionProductType.GAUGE`
- move unique product identifiers to new `DfuProductType` used for DFU related logic and where differentiate between display and booster

Refactor product types

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/GaugeManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/GaugeStatus.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/NodeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeRequest.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/log/LogManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionService.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/DeviceManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/Gauge.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/HighLowAlarmStatus.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/LoggedDataPoint.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/LoggedGaugeDataPoint.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/LoggedProbeDataPoint.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/Probe.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/SpecializedDevice.kt

- merge to feature branch
- matching app PR https://github.com/combustion-inc/combustion-android-prod/pull/322
- Support linking/unlinking gauge
- make framework more robust to being accessed while still initializing
- add support for missing gauge status properties for cloud
- fix requesting gauge logs not firing
- `doWhenNetworkManagerInitialized()` delays executing until `NetworkManager` has been initialized
- add gauge to `unlinkDevice()` logic

DROID-581 : more linking support for Gauge

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/CombustionProductType.kt

- Fix app v2.5.1 (pre gauge support) thinks Gauge is an overheating probe
- When handling advertisements ignore those from product types that are not supported, i.e. only consider PROBE and DISPLAY (renamed to NODE in gauge branch)

Fix app v2.5.1 thinks Gauge is an overheating probe

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/BleManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/GaugeDataLinkArbitrator.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/GaugeManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/GaugeStatus.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/ProbeManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/GaugeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/NodeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/SimulatedGaugeBleDevice.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/UartCapableGauge.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/uart/meatnet/NodeReadGaugeLogsResponse.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/Gauge.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/Probe.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/SensorTemperature.kt
combustion-android-ble/src/main/java/inc/combustion/framework/service/SpecializedDevice.kt
combustion-android-ble/src/test/java/inc/combustion/framework/service/SensorTemperatureTest.kt

- Send gauge's setHighLowAlarmStatus and sendLogRequest calls to all connected meatnet nodes if directLink is not available.
- when gauge sensor not present then parse temperature as no data value
- `NetworkManager` now calls new `GaugeDataLinkArbitrator.addRepeaterNodes()`
- In `GaugeManager.setHighLowAlarmStatus()` and `GaugeManager.sendLogRequest()`, if `GaugeDataLinkArbitrator.directLink` is not available then message is sent to all `GaugeDataLinkArbitrator.connectedNodeLinks`

DROID-644: Add full meatnet support to gauges

---

combustion-android-ble/src/main/java/inc/combustion/framework/ble/NetworkManager.kt
combustion-android-ble/src/main/java/inc/combustion/framework/ble/device/NodeBleDevice.kt

- Fix unknown device type crash when updating connected nodes
- unlinking gauge, which is a hybrid node device, removed reference to its node component (same mac) which is still "used" by devices

DROID-638 : fix Unknown device type crash when updating connected nodes

---

combustion-android-ble/src/main/java/inc/combustion/framework/log/Session.kt

- make `Session.dataPoints` threadsafe
- required by app PR https://github.com/combustion-inc/combustion-android-prod/pull/349

DROID-672: make `Session.dataPoints` threadsafe
